config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  post 'signup', to: 'users#create'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get '*unmatched_route', to: 'application#not_found'
  get '/', to: 'users#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include ApplicationHelper

  has_secure_password
  PASSWORD_REQUIREMENTS = /\A
  (?=.{8,})
  (?=.*\d)
  (?=.*[a-z])
  (?=.*[A-Z])
  (?=.*[[:^alnum:]])
  /x
  ROLES ||= { beneficiario: 0, padrino: 1 }.freeze
  enum role: ROLES

  validates :name, length: {minimum: 3}
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i }
  validates :identification, uniqueness: true
  validates :phone_number, uniqueness: true
  validates :password, format: PASSWORD_REQUIREMENTS
  serialize :email_status
  serialize :sms_status

  after_create :send_notification, :update_notification_status

  def self.search(param)
    User.where('name LIKE :input OR email LIKE :input', input: "%#{param}%")
  end

  def send_notification
    SendTextMessageJob.set(wait_until: 1.minutes.from_now).perform_later(phone_number) if beneficiario?
    SendEmailJob.set(wait_until: 1.minutes.from_now).perform_later(email) if padrino?
  end

  def notification_message
    return "No se ha enviado la notificación" if sms_status.nil? && email_status.nil?
    return "No se ha enviado el sms" if sms_status && sms_status[:code].nil? && beneficiario?
    return "No se ha enviado el email" if email_status && email_status[:code].nil? && padrino?
    return "El sms ha sido enviado" if sms_status && sms_status[:notified] && beneficiario?
    return "El sms ha sido enviado" if email_status && email_status[:notified] && padrino?
    return "El mensaje se ha enviado satisfactoriamente" if sms_status && email_status && sms_status[:notified] && email_status[:notified]
    return "Hubo un error al enviar el mensaje"
  end

  def status_code
    return "" if sms_status.nil? && email_status.nil?
    return sms_status[:code] if beneficiario? && sms_status[:notified] 
    return email_status[:code] if padrino? && email_status[:notified]
    return ""
  end

  def update_notification_status
    hash = {
      notified: false,
      code: nil,
      response: "Sent"
    }
    update(sms_status: hash) if beneficiario?
    update(email_status: hash) if padrino?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def not_found
    render "404"
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render 'new'
    end

    rescue ActiveRecord::RecordNotUnique
      flash.now[:alert] = 'El usuario ya existe en el sistema'
      render 'new'
  end

  def index
    return nil if params[:search].nil?
    @users = User.search(params[:search])
  end

  def show
  end

  private
  def user_params
    up = params.require(:user).permit(:name, :password, :password_confirmation, :email, :identification, :phone_number, :role, :search)
    up[:role] = up[:role].to_i
    up
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notification_success(notification)
    (200..299).include?(notification) ? true : false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/404.html.erb
<h1>Página no encontrada</h1>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-lg navbar-light bg-light'>
  <div class='collapse navbar-collapse' id='navbarNavAltMarkup'>
    <div class='navbar-nav'>
      <p class='nav-item nav-link active'%> <%= "Hola, #{current_user.name}" if current_user%> </p>
      <a class='navbar-brand' href= <%= root_path%>>Home</a>
        <% if current_user %>
          <a class='nav-item nav-link active' href=<%= logout_path %>>Cerrar Sesión <span class='sr-only'>(current)</span></a>
        <% else %>
          <a class='nav-item nav-link active' href=<%= login_path %>>Iniciar Sesión</a>
          <a class='nav-item nav-link active' href=<%= signup_path %>>Registro</a>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zinobe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
     <%= render 'layouts/header' %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<% if current_user %>
  <div class='row '>
    <div class= 'col-md-5'>
      Buscar Usuarios
    <%= form_tag(users_path, method: :get) do %>
      <%= text_field_tag(:search, params[:search]) %>
      <%= submit_tag('Buscar') %>
      <%= button_tag('Limpiar', type: 'button', class: 'limpiar') %>

    <% end %>

    <% if @users.present? %>
      <% @users.each do |u| %>
        <ul class = 'search-results'>
          <li> <%= "#{u.name} - #{u.email}" %></li>
        </ul>
      <% end %>
      <%= 'Su búsqueda no arrojó resultados' if @users.empty?%>
    <% end %>
    </div>
    <div id = "notifications">
      Notificación <br />
    <% if current_user.sms_status.present?  || current_user.email_status.present?%>
      <ul>
        <li><%= "Código: #{current_user.status_code}" %></li>
        <li><%= "Mensaje: #{current_user.notification_message}"%></li>
      </ul>
    <% end %>

    </div>
  </div>
<% else %>
 <h3> Por favor <a href=<%= login_path %>>inicie sesión</a> o <a href=<%= signup_path %>> regístrese</a> para continuar</h1>
<% end %>

app/views/users/new.html.erb
<% if !current_user %>
  <h1>Registro</h1>

  <p id=”alert”><%= alert %></p>

  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name, "Nombre" %><br />
      <%= f.text_field :name, required: true%>
    </div>
    <div class="field">
      <%= f.label :email, "Correo electrónico" %><br />
      <%= f.text_field :email, required: true %>
    </div>
    <div class="field">
      <%= f.label :password, "Contraseña" %><br />
      <%= f.password_field :password, required: true %>
      <i class="fa fa-info-circle" title="Debe contener al menos 1 mayúscula, 1 número y 1 símbolo" data-toggle="tooltip" data-placement="right" aria-hidden="true"></i>  
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Confirme su contraseña" %><br />
      <%= f.password_field :password_confirmation, required: true %>
    </div>
    <div class="field">
      <%= f.label :identification, "Número de cédula" %><br />
      <%= f.text_field :identification, required: true %>
    </div>
    <div class="field">
      <%= f.label :phone_number, "Número celular" %><br />
      <%= f.text_field :phone_number, required: true %>
    </div>
    <br />
    <div class="field">
      <%= f.select(:role, User.roles.keys.map { |k| k.humanize }, {include_blank: "Tipo de Usuario"}, {required: true}) %>
    </div>
    <br />
    <div class="actions"><%= f.submit "Sign Up" %></div>
  <% end %>
<% else %>
  <h1>Ya has iniciado sesión</h1>
<% end %>

<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script> 